### ISSUE TITLE
Cannot install Forum w/o Vendors installed

### ISSUE THREAD

**Issue by roman-yagodin** [DNNCommunity/DNN.Forum#6]
Tried to do clean install on DNN 8.0.4, resulted in following error (sorry, some text translated from russian with Google, as .NET uses system language in error messages):

```
SQL Execution resulted in following Exceptions: System.Data.SqlClient.SqlException (0x80131904):
The foreign key "FK_Forum_Ad_Vendors_Vendors" refers to an invalid table "dbo.Vendors".
You can not create constraint. See previous errors. 
at System.Data.SqlClient.SqlConnection.OnError (SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning (TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun (RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean & dataReady)
at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds (String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
at System.Data.SqlClient .SqlCommand.InternalExecuteNonQuery (TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery ()
at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal (String connectionString, String script)
ClientConnectionId : c10a568d-6374-4498-8cb2-40758b25c43a
Error Number: 1767, State: 0,
Class: 16 ALTER TABLE dbo.Forum_Ad_Vendors ADD CONSTRAINT FK_Forum_Ad_Vendors_Vendors FOREIGN KEY ([VendorID]) REFERENCES dbo.Vendors ([VendorID]) ON DELETE CASCADE
```

I think dependency on Vendors should be declared in the manifest. 

I also should note here that separate [Vendors](https://github.com/DNNCommunity/DNN.Vendors) module for DNN 8 have its own issues with clean install, so there is no simple way to do clean install of Forum module currently.

**Comment by juvander** [comment]
Actually, Vendor module reference was removed already earlier, will fix this sql stuff in a minute.

**Comment by roman-yagodin** [comment]
Thanks, @juvander

**Comment by juvander** [comment]
Fixed in here https://github.com/juvander/DotNetNuke-Forum/releases/tag/05.00.07_DNN8

**Comment by roman-yagodin** [comment]
Cool, I'll test it later.

**Comment by roman-yagodin** [comment]
No luck, there is still an error on install when `05.00.01.SqlDataProvider` executed.

Install log:

```
Installation Failed - ScriptPackage Installation Report
See below for the results of the package installation.
Error loading files from temporary folder - see below.
StartJob 	Starting Installation
Info 	Starting Installation - DNN_Forum
Info 	Starting Installation - Script
Info 	Begin Sql execution
Info 	Folder Created - C:\Dotnetnuke804\DesktopModules\Forum\Providers\DataProviders\SqlDataProvider
Info 	Created - Providers\DataProviders\SqlDataProvider\03.00.00.SqlDataProvider
Info 	Executing 03.00.00.SqlDataProvider
Info 	Start Sql execution: 03.00.00.SqlDataProvider file
Info 	End Sql execution: 03.00.00.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\03.10.05.SqlDataProvider
Info 	Executing 03.10.05.SqlDataProvider
Info 	Start Sql execution: 03.10.05.SqlDataProvider file
Info 	End Sql execution: 03.10.05.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.03.00.SqlDataProvider
Info 	Executing 04.03.00.SqlDataProvider
Info 	Start Sql execution: 04.03.00.SqlDataProvider file
Info 	End Sql execution: 04.03.00.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.03.04.SqlDataProvider
Info 	Executing 04.03.04.SqlDataProvider
Info 	Start Sql execution: 04.03.04.SqlDataProvider file
Info 	End Sql execution: 04.03.04.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.04.03.SqlDataProvider
Info 	Executing 04.04.03.SqlDataProvider
Info 	Start Sql execution: 04.04.03.SqlDataProvider file
Info 	End Sql execution: 04.04.03.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.04.04.SqlDataProvider
Info 	Executing 04.04.04.SqlDataProvider
Info 	Start Sql execution: 04.04.04.SqlDataProvider file
Info 	End Sql execution: 04.04.04.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.05.00.SqlDataProvider
Info 	Executing 04.05.00.SqlDataProvider
Info 	Start Sql execution: 04.05.00.SqlDataProvider file
Info 	End Sql execution: 04.05.00.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.05.02.SqlDataProvider
Info 	Executing 04.05.02.SqlDataProvider
Info 	Start Sql execution: 04.05.02.SqlDataProvider file
Info 	End Sql execution: 04.05.02.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.06.01.SqlDataProvider
Info 	Executing 04.06.01.SqlDataProvider
Info 	Start Sql execution: 04.06.01.SqlDataProvider file
Info 	End Sql execution: 04.06.01.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.07.00.SqlDataProvider
Info 	Executing 04.07.00.SqlDataProvider
Info 	Start Sql execution: 04.07.00.SqlDataProvider file
Info 	End Sql execution: 04.07.00.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.09.00.SqlDataProvider
Info 	Executing 04.09.00.SqlDataProvider
Info 	Start Sql execution: 04.09.00.SqlDataProvider file
Info 	End Sql execution: 04.09.00.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\04.09.01.SqlDataProvider
Info 	Executing 04.09.01.SqlDataProvider
Info 	Start Sql execution: 04.09.01.SqlDataProvider file
Info 	End Sql execution: 04.09.01.SqlDataProvider file
Info 	Created - Providers\DataProviders\SqlDataProvider\05.00.01.SqlDataProvider
Info 	Executing 05.00.01.SqlDataProvider
Info 	Start Sql execution: 05.00.01.SqlDataProvider file
Failure 	SQL Execution resulted in following Exceptions: System.Data.SqlClient.SqlException (0x80131904): A foreign key "FK_Forum_Ad_Vendors_Vendors" refers to an invalid table "dbo.Vendors". You can not create constraint. See previous errors. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:0985717d-b6b0-49ea-9d51-56a6b8b5ca75 Error Number:1767,State:0,Class:16 ALTER TABLE dbo.Forum_Ad_Vendors ADD CONSTRAINT FK_Forum_Ad_Vendors_Vendors FOREIGN KEY ( [VendorID] ) REFERENCES dbo.Vendors ( [VendorID] ) ON DELETE CASCADE
Info 	End Sql execution: 05.00.01.SqlDataProvider file
Info 	Finished Sql execution
Failure 	Installation Failed - Script
Info 	Installation Failed - DNN_Forum
Info 	Deleted temporary install folder
EndJob 	Installation Failed
```

**Comment by juvander** [comment]
Download the package again, managed to update my dev to DNN9 and now for some reason it won't install at all... so could not test it at all.

**Comment by roman-yagodin** [comment]
Now it's working, thanks @juvander!
